from __future__ import annotations

import hashlib
import json
import warnings
from pathlib import Path
from typing import Any, Sequence

import numpy as np
import pandas as pd

from lib.indicators import compute_diagnostics


SCENARIOS = ("integrable_potential", "nonintegrable_vorticity", "proxy_misspecified")
NOISE_LEVELS = (0.0, 0.02, 0.05, 0.10)
SAMPLING_STEPS = (1, 2, 4)
DEFAULT_WINDOW = 16
NONINTEGRABLE_OMEGA = 0.55
PROXY_STRENGTH = 0.35


def _stable_seed(*parts: Any, base_seed: int = 10_337) -> int:
    payload = "|".join(str(part) for part in parts)
    digest = hashlib.sha256(payload.encode("utf-8")).hexdigest()
    return (int(digest[:12], 16) + int(base_seed)) % (2**32 - 1)


def _base_state(n: int) -> tuple[np.ndarray, np.ndarray]:
    idx = np.arange(n, dtype=float)
    t = np.linspace(0.0, 10.0 * np.pi, n, endpoint=False)
    s = 10.0 + 0.018 * idx + 1.60 * np.sin(t) + 0.35 * np.sin(2.3 * t)
    v = 7.0 + 0.014 * idx + 1.25 * np.cos(1.4 * t) + 0.30 * np.sin(2.7 * t)
    return s, v


def _standardize(values: np.ndarray) -> np.ndarray:
    arr = np.asarray(values, dtype=float)
    sd = float(np.std(arr, ddof=0))
    if not np.isfinite(sd) or sd <= 0.0:
        return np.zeros_like(arr, dtype=float)
    return (arr - float(np.mean(arr))) / sd


def _add_noise(values: np.ndarray, *, noise_level: float, rng: np.random.Generator) -> np.ndarray:
    arr = np.asarray(values, dtype=float)
    if noise_level <= 0.0:
        return arr.copy()
    scale = float(np.std(arr, ddof=0))
    if not np.isfinite(scale) or scale <= 0.0:
        scale = 1.0
    return arr + float(noise_level) * scale * rng.normal(0.0, 1.0, size=arr.size)


def generate_synthetic_integrability_frame(
    *,
    scenario: str,
    noise_level: float = 0.0,
    sampling_step: int = 1,
    n_base: int = 240,
    seed: int = 10_337,
    nonintegrable_omega: float = NONINTEGRABLE_OMEGA,
    proxy_strength: float = PROXY_STRENGTH,
) -> pd.DataFrame:
    """Generate a synthetic panel for the Maxwell/vorticity diagnostic.

    The baseline uses the quadratic potential U(S,V)=aS^2+bSV+cV^2, so
    T=dU/dS and p=-dU/dV satisfy dT/dV + dp/dS = 0 exactly. The
    nonintegrable case adds a rotational p-component with known curl. The
    proxy-misspecified case keeps the latent potential integrable but contaminates
    the observed liquidity proxy, so non-zero curl should be read as a proxy warning.
    """
    scenario = str(scenario).strip().lower()
    if scenario not in SCENARIOS:
        raise ValueError(f"unknown integrability scenario: {scenario}")
    step = max(1, int(sampling_step))
    rng = np.random.default_rng(seed)

    s, v = _base_state(int(n_base))
    a, b, c = 0.42, -0.68, 0.31
    u = a * s**2 + b * s * v + c * v**2
    tl = 2.0 * a * s + b * v
    pc = -(b * s + 2.0 * c * v)

    latent_omega = 0.0
    expected_observed_omega = 0.0
    proxy_flag = False
    if scenario == "nonintegrable_vorticity":
        pc = pc + float(nonintegrable_omega) * s
        latent_omega = float(nonintegrable_omega)
        expected_observed_omega = float(nonintegrable_omega)
    elif scenario == "proxy_misspecified":
        proxy_flag = True
        # A nonlinear proxy contamination is not generated by the latent
        # quadratic potential, so it should raise a consistency warning.
        tl = tl + float(proxy_strength) * float(np.std(tl, ddof=0)) * _standardize(s) * _standardize(v)
        expected_observed_omega = float("nan")

    tl_obs = _add_noise(tl, noise_level=float(noise_level), rng=rng)
    pc_obs = _add_noise(pc, noise_level=float(noise_level), rng=rng)
    frame = pd.DataFrame(
        {
            "date": pd.date_range("2000-03-31", periods=int(n_base), freq="QE-DEC"),
            "S_M": s,
            "V_C": v,
            "T_L": tl_obs,
            "p_C": pc_obs,
            "U": u,
            "scenario": scenario,
            "noise_level": float(noise_level),
            "sampling_step": int(step),
            "latent_omega": latent_omega,
            "expected_observed_omega": expected_observed_omega,
            "proxy_misspecified": proxy_flag,
        }
    )
    return frame.iloc[::step].reset_index(drop=True)


def evaluate_integrability_synthetic_case(
    *,
    scenario: str,
    noise_level: float = 0.0,
    sampling_step: int = 1,
    window: int = DEFAULT_WINDOW,
    seed: int = 10_337,
) -> dict[str, Any]:
    frame = generate_synthetic_integrability_frame(
        scenario=scenario,
        noise_level=noise_level,
        sampling_step=sampling_step,
        seed=seed,
    )
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=FutureWarning, message=".*ChainedAssignmentError.*")
        out = compute_diagnostics(frame.copy(deep=True), window=window)
    omega = pd.to_numeric(out.get("maxwell_curl"), errors="coerce").dropna()
    dtdv = pd.to_numeric(out.get("dT_dV_at_S"), errors="coerce").dropna()
    dpds = pd.to_numeric(out.get("dp_dS_at_V"), errors="coerce").dropna()
    target = float(frame["expected_observed_omega"].iloc[0])
    latent = float(frame["latent_omega"].iloc[0])

    if omega.empty:
        mean_omega = median_omega = mean_abs = median_abs = max_abs = rmse = float("nan")
    else:
        mean_omega = float(omega.mean())
        median_omega = float(omega.median())
        abs_omega = omega.abs()
        mean_abs = float(abs_omega.mean())
        median_abs = float(abs_omega.median())
        max_abs = float(abs_omega.max())
        rmse = (
            float(np.sqrt(np.mean((omega.to_numpy(dtype=float) - target) ** 2)))
            if np.isfinite(target)
            else float("nan")
        )

    tolerance = 1e-8 if float(noise_level) == 0.0 else 0.08 + 2.5 * float(noise_level)
    if scenario == "integrable_potential":
        decision = "passes_zero_curl" if np.isfinite(mean_abs) and mean_abs <= tolerance else "too_noisy_or_biased"
    elif scenario == "nonintegrable_vorticity":
        err = abs(mean_omega - target) if np.isfinite(mean_omega) and np.isfinite(target) else float("inf")
        decision = "detects_nonintegrable" if err <= tolerance and np.sign(mean_omega) == np.sign(target) else "misses_vorticity"
    else:
        decision = "proxy_warning" if np.isfinite(mean_abs) and mean_abs > 0.05 else "proxy_warning_weak"

    return {
        "scenario": scenario,
        "scenario_label": {
            "integrable_potential": "known potential",
            "nonintegrable_vorticity": "non-integrable field",
            "proxy_misspecified": "proxy misspecified",
        }.get(scenario, scenario),
        "noise_level": float(noise_level),
        "sampling_step": int(sampling_step),
        "window": int(window),
        "n_obs": int(len(frame)),
        "n_valid": int(len(omega)),
        "latent_omega": latent,
        "expected_observed_omega": target,
        "mean_omega": mean_omega,
        "median_omega": median_omega,
        "mean_abs_omega": mean_abs,
        "median_abs_omega": median_abs,
        "max_abs_omega": max_abs,
        "rmse_to_expected": rmse,
        "mean_dT_dV_at_S": float(dtdv.mean()) if not dtdv.empty else float("nan"),
        "mean_dp_dS_at_V": float(dpds.mean()) if not dpds.empty else float("nan"),
        "proxy_misspecified": bool(frame["proxy_misspecified"].iloc[0]),
        "decision": decision,
    }


def run_integrability_synthetic_test(
    *,
    scenarios: Sequence[str] = SCENARIOS,
    noise_levels: Sequence[float] = NOISE_LEVELS,
    sampling_steps: Sequence[int] = SAMPLING_STEPS,
    window: int = DEFAULT_WINDOW,
    seed: int = 10_337,
) -> pd.DataFrame:
    rows: list[dict[str, Any]] = []
    for scenario in scenarios:
        for noise_level in noise_levels:
            for sampling_step in sampling_steps:
                case_seed = _stable_seed(scenario, noise_level, sampling_step, base_seed=seed)
                rows.append(
                    evaluate_integrability_synthetic_case(
                        scenario=scenario,
                        noise_level=float(noise_level),
                        sampling_step=int(sampling_step),
                        window=window,
                        seed=case_seed,
                    )
                )
    return pd.DataFrame(rows)


def summarize_integrability_synthetic(results: pd.DataFrame) -> dict[str, Any]:
    if results.empty:
        return {"overall": {}, "scenarios": {}, "interpretation": "No synthetic integrability rows were produced."}

    def finite_or_none(value: Any) -> float | None:
        try:
            val = float(value)
        except Exception:
            return None
        return val if np.isfinite(val) else None

    clean = results[results["noise_level"].eq(0.0)].copy()
    scenario_summary: dict[str, Any] = {}
    for scenario, group in results.groupby("scenario", sort=True):
        mean_abs = pd.to_numeric(group["mean_abs_omega"], errors="coerce")
        rmse = pd.to_numeric(group["rmse_to_expected"], errors="coerce")
        scenario_summary[scenario] = {
            "rows": int(len(group)),
            "max_mean_abs_omega": finite_or_none(mean_abs.max()) if mean_abs.notna().any() else None,
            "median_mean_abs_omega": finite_or_none(mean_abs.median()) if mean_abs.notna().any() else None,
            "max_rmse_to_expected": finite_or_none(rmse.max()) if rmse.notna().any() else None,
            "decisions": sorted(str(item) for item in group["decision"].dropna().unique()),
        }

    zero_clean = clean[clean["scenario"].eq("integrable_potential")]
    nonint_clean = clean[clean["scenario"].eq("nonintegrable_vorticity")]
    proxy_clean = clean[clean["scenario"].eq("proxy_misspecified")]
    clean_zero_pass = bool(
        not zero_clean.empty
        and pd.to_numeric(zero_clean["mean_abs_omega"], errors="coerce").max() <= 1e-8
    )
    clean_nonint_pass = bool(
        not nonint_clean.empty
        and (pd.to_numeric(nonint_clean["mean_omega"], errors="coerce") - NONINTEGRABLE_OMEGA).abs().max() <= 1e-8
    )
    clean_proxy_flags = bool(
        not proxy_clean.empty
        and pd.to_numeric(proxy_clean["mean_abs_omega"], errors="coerce").min() > 0.05
    )
    return {
        "overall": {
            "rows": int(len(results)),
            "noise_levels": sorted(float(x) for x in results["noise_level"].dropna().unique()),
            "sampling_steps": sorted(int(x) for x in results["sampling_step"].dropna().unique()),
            "clean_integrable_zero_curl_pass": clean_zero_pass,
            "clean_nonintegrable_detection_pass": clean_nonint_pass,
            "clean_proxy_warning_pass": clean_proxy_flags,
        },
        "scenarios": scenario_summary,
        "interpretation": (
            "The local-linear Maxwell/vorticity diagnostic is exact on clean quadratic-potential "
            "data, detects the designed non-integrable rotational component, and rises when the "
            "observed proxies are contaminated even though the latent potential is integrable."
        ),
    }


def _fmt(value: Any, digits: int = 3) -> str:
    try:
        val = float(value)
    except Exception:
        return ""
    if not np.isfinite(val):
        return ""
    if abs(val) >= 100_000 or (0 < abs(val) < 0.001):
        return f"{val:.{digits}e}"
    return f"{val:.{digits}f}"


def _latex_escape(value: Any) -> str:
    return (
        str(value)
        .replace("\\", "\\textbackslash{}")
        .replace("_", "\\_")
        .replace("&", "\\&")
        .replace("%", "\\%")
    )


def render_integrability_synthetic_tex(results: pd.DataFrame) -> str:
    if results.empty:
        return "% Integrability synthetic table unavailable.\n"
    table = results[
        results["noise_level"].isin([0.0, 0.05])
        & results["sampling_step"].isin([1, 4])
    ].copy()
    table = table.sort_values(["scenario", "noise_level", "sampling_step"])
    lines = [
        "\\begin{table}[htbp]",
        "  \\centering",
        "  \\small",
        "  \\setlength{\\tabcolsep}{3pt}",
        "  \\caption{Synthetic integrability and vorticity validation.}",
        "  \\label{tab:integrability_synthetic}",
        "  \\resizebox{\\textwidth}{!}{%",
        "  \\begin{tabular}{@{}lllllllll@{}}",
        "    \\toprule",
        "    Case & Noise & Step & $N$ & Target $\\Omega$ & Mean $\\Omega$ & Mean $|\\Omega|$ & RMSE & Decision \\\\",
        "    \\midrule",
    ]
    for _, row in table.iterrows():
        target = row["expected_observed_omega"]
        target_text = "proxy" if not np.isfinite(float(target)) else _fmt(target)
        lines.append(
            "    "
            + " & ".join(
                [
                    _latex_escape(row["scenario_label"]),
                    _fmt(row["noise_level"], digits=2),
                    str(int(row["sampling_step"])),
                    str(int(row["n_obs"])),
                    target_text,
                    _fmt(row["mean_omega"]),
                    _fmt(row["mean_abs_omega"]),
                    _fmt(row["rmse_to_expected"]),
                    _latex_escape(row["decision"].replace("_", " ")),
                ]
            )
            + " \\\\"
        )
    lines.extend(
        [
            "    \\bottomrule",
            "  \\end{tabular}",
            "  }",
            "  \\par\\smallskip\\raggedright\\footnotesize "
            "Rows are generated from $U(S,V)=aS^2+bSV+cV^2$, with "
            "$T=\\partial U/\\partial S$ and $p=-\\partial U/\\partial V$. "
            "The non-integrable case adds a rotational component with target "
            f"$\\Omega={NONINTEGRABLE_OMEGA:.2f}$. The proxy row keeps the latent potential "
            "integrable but contaminates the observed liquidity proxy, so non-zero curl is "
            "interpreted as a proxy-consistency warning rather than proof of physical vorticity. "
            "The companion CSV reports the full noise and sampling-frequency grid.",
            "\\end{table}",
        ]
    )
    return "\n".join(lines) + "\n"


def _json_default(value: Any) -> Any:
    if isinstance(value, (np.integer,)):
        return int(value)
    if isinstance(value, (np.floating,)):
        val = float(value)
        return None if not np.isfinite(val) else val
    if isinstance(value, float) and not np.isfinite(value):
        return None
    return str(value)


def write_integrability_synthetic_outputs(results: pd.DataFrame, *, root: Path) -> list[Path]:
    site_dir = root / "site"
    data_dir = root / "data"
    tex_dir = root / "tex" / "generated"
    site_dir.mkdir(parents=True, exist_ok=True)
    data_dir.mkdir(parents=True, exist_ok=True)
    tex_dir.mkdir(parents=True, exist_ok=True)

    csv_path = site_dir / "integrability_synthetic_test.csv"
    json_path = data_dir / "integrability_synthetic_summary.json"
    tex_path = tex_dir / "theory_integrability_synthetic_test.tex"

    results.to_csv(csv_path, index=False)
    json_path.write_text(
        json.dumps(
            summarize_integrability_synthetic(results),
            indent=2,
            sort_keys=True,
            default=_json_default,
            allow_nan=False,
        ),
        encoding="utf-8",
    )
    tex_path.write_text(render_integrability_synthetic_tex(results), encoding="utf-8")
    return [csv_path, json_path, tex_path]
